// Generated by https://quicktype.io

export interface Categories {
    categories: Category[];
}

export interface Category {
    idCategory:             string;
    strCategory:            string;
    strCategoryThumb:       string;
    strCategoryDescription: string;
}
